name: Unit testing, formatting & linting
on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - "12"
          - "14"
          - "16"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - run: yarn
      - run: yarn test
      - run: yarn run lint
      - run: yarn run build
